### ISSUE TITLE
Chapter 1 Networking Fundamentals: Page 14 [Errata]

### ISSUE THREAD

**Issue by james-hsiung** [benpiper/benpiper.github.io#1]
**Please describe the error you're reporting**
Hi Ben,

How are you? 

1. Host A compares its IP address with "Router B's IP" //May I ask whether the correct description should be "Host B's IP" instead of "Router B's IP"? Thanks. 

**Please indicate the chapter or appendix, section, and page number where the error appears (if applicable)**
Chapter 1, Page 14, Forwarding between Subnets 
**Please include any other comments or questions**

Best Regards,
James

**Comment by benpiper** [comment]
You are correct. I've updated the errata. Thank you!
